[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ubuntu/keys/terra-key-ansible

[control]
control-node-ubuntu ansible_connection=local ansible_user=ubuntu

[ubuntu_workers]
worker-ubuntu ansible_host=172.31.32.252 ansible_user=ubuntu

[redhat]
worker-redhat ansible_host=172.31.37.108 ansible_user=ec2-user

[amazon]
worker-amazon ansible_host=172.31.47.172 ansible_user=ec2-user

[workers:children]
ubuntu_workers
redhat
amazon

[ubuntu:children]
control
ubuntu_workers


